#define { package-version: 2.2.0.2; }

#define { author-version: "2.2.0-1"; }

#define { outercurve-publickeytoken: "1e373a58e25250cb"; }

#define { deps-publickeytoken: "${outercurve-publickeytoken}"; }

#define { glib-dep-version: "2.32.3.2"; }

#define { glib-dep-publickeytoken: "${deps-publickeytoken}"; }

#define { libintl-dep-version: "0.18.1"; }

#define { libintl-dep-publickeytoken: "${deps-publickeytoken}"; }
